apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backup.fullname" . }}
  labels:
    {{- include "backup.labels" . | nindent 4 }}
data:
  brudi.yaml: |-
  {{- if .Values.brudi.config }}
    {{ tpl .Values.brudi.config . | nindent 4 }}
  {{- end }}