apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "backup.fullname" . }}
  labels:
    {{- include "backup.labels" . | nindent 4 }}
    {{- with .Values.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "backup.labels" . | nindent 12 }}
          {{- with .Values.additionalLabels }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          restartPolicy: {{ .Values.cronjob.restartPolicy | quote }}
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.nodeSelector }}
          nodeSelector:
            {{ toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          volumes:
            - name: config-volume
              configMap:
                name: {{ include "backup.fullname" . }}
                items:
                  - key: "brudi.yaml"
                    path: "brudi.yaml"
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              command:
                - "brudi"
              args:
                - {{ .Values.brudi.cli.command | quote }}
                - "-c"
                - "/etc/config/brudi.yaml"
                {{-  if .Values.brudi.cli.restic }}
                - "--restic"
                {{-  end }}
                {{-  if .Values.brudi.cli.cleanup }}
                - "--cleanup"
                {{-  end }}
              env:
              {{- with .Values.additionalEnv }}
                {{- toYaml . | nindent 16 }}
              {{- end }}
              volumeMounts:
                - name: config-volume
                  mountPath: /etc/config