{{- if .Values.serviceAccount.create -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
subjects:
    - kind: ServiceAccount
      name: {{ include "chart.fullname" . }}
roleRef:
    kind: Role
    name: {{ include "chart.fullname" . }}
    apiGroup: rbac.authorization.k8s.io
{{- end -}}