name: Push latest Brudi-Operator

on:
  push:
    branches:
      - master

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install requirements
        run: bash $(pwd)/scripts/requirements.sh

      - name: Log into registry
        run: |
          docker login -u="${{ secrets.QUAY_IO_USER }}" -p="${{ secrets.QUAY_IO_TOKEN }}" quay.io

      - name: Push brudi-operator latest
        env:
          PUSH: "true"
        run: bash $(pwd)/scripts/docker-build-tag.sh latest
